# Generated by Django 5.2.12 on 2026-06-05 11:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('tag', models.CharField(choices=[('standard', 'Regulatory Standard'), ('announcement', 'Training / Announcement'), ('update', 'System Update')], default='standard', max_length=50)),
                ('description', models.TextField()),
                ('link_url', models.URLField(blank=True, help_text='Optional link to full article or document')),
                ('link_text', models.CharField(default='Read More', help_text='Text to display for the link', max_length=100)),
                ('image', models.ImageField(blank=True, help_text='Optional image representing the news item', null=True, upload_to='news/')),
                ('is_published', models.BooleanField(default=True)),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_date', '-created_at'],
            },
        ),
    ]
