# Generated by Django 5.2.12 on 2026-03-30 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20260330_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='old_role',
        ),
        migrations.AlterField(
            model_name='user',
            name='role_obj',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.role'),
            preserve_default=False,
        ),
    ]
