# Generated by Django 4.2.11 on 2026-03-11 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_industry_category'),
        ('forms_builder', '0002_alter_formassignment_unique_together_and_more'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question_label_snapshot',
            field=models.CharField(blank=True, help_text='Question label snapshotted at submission time. Preserves history if form is edited later.', max_length=500),
        ),
        migrations.AddField(
            model_name='submission',
            name='form_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The factory/organization this report belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='accounts.industry'),
        ),
        migrations.AddField(
            model_name='submission',
            name='period',
            field=models.ForeignKey(blank=True, help_text='The reporting period this submission covers (e.g., March 2026)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='forms_builder.reportingperiod'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='food_category',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', False), ('period__isnull', False)), fields=('form', 'period', 'organization'), name='unique_submission_per_org_per_period'),
        ),
    ]
