# Generated by Django 4.2.11 on 2026-03-11 (V2 Architecture)

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_industry_category'),
        ('forms_builder', '0001_initial'),
    ]

    operations = [
        # Step 1: Remove the old string-based category CharField
        # (it's NOT NULL so we can't AlterField directly - must RemoveField + AddField)
        migrations.RemoveField(
            model_name='form',
            name='category',
        ),
        # Step 2: Add the new FK-based category field (nullable)
        migrations.AddField(
            model_name='form',
            name='category',
            field=models.ForeignKey(
                blank=True, null=True,
                help_text='Leave blank for forms applicable to all categories',
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='forms',
                to='accounts.category'
            ),
        ),
        # Step 3: Remove old schedule_day field
        migrations.RemoveField(
            model_name='form',
            name='schedule_day',
        ),
        # Step 4: Add new submission window fields
        migrations.AddField(
            model_name='form',
            name='opens_on_day',
            field=models.PositiveIntegerField(default=1, help_text='Day of period the form opens (1=start)'),
        ),
        migrations.AddField(
            model_name='form',
            name='due_on_day',
            field=models.PositiveIntegerField(default=10, help_text='Day of period the submission is due'),
        ),
        migrations.AddField(
            model_name='form',
            name='closes_on_day',
            field=models.PositiveIntegerField(default=15, help_text='Day of period the form locks (no more submissions)'),
        ),
        # Step 5: Add form versioning
        migrations.AddField(
            model_name='form',
            name='version',
            field=models.PositiveIntegerField(default=1, help_text='Increment when form questions change significantly'),
        ),
        # Step 6: Extend schedule choices
        migrations.AlterField(
            model_name='form',
            name='schedule_type',
            field=models.CharField(
                choices=[
                    ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'),
                    ('quarterly', 'Quarterly'), ('biannual', 'Bi-Annual'), ('annual', 'Annual'),
                ],
                default='monthly', max_length=20
            ),
        ),
        # Step 7: Upgrade FormAssignment - reset unique_together, add industry FK
        migrations.AlterUniqueTogether(
            name='formassignment',
            unique_together={('form', 'user')},
        ),
        migrations.RemoveField(
            model_name='formassignment',
            name='due_date',
        ),
        migrations.AddField(
            model_name='formassignment',
            name='industry',
            field=models.ForeignKey(
                blank=True, null=True,
                help_text='Assign to a specific factory. If blank, applies via category.',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='form_assignments',
                to='accounts.industry'
            ),
        ),
        migrations.AlterField(
            model_name='formassignment',
            name='user',
            field=models.ForeignKey(
                blank=True, null=True,
                help_text='Assign to a specific user (overrides industry assignment)',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='form_assignments',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name='formassignment',
            unique_together={('form', 'industry'), ('form', 'user')},
        ),
        # Step 8: Clean up question field
        migrations.AlterField(
            model_name='question',
            name='depends_on_value',
            field=models.CharField(blank=True, max_length=200),
        ),
        # Step 9: Create the ReportingPeriod model
        migrations.CreateModel(
            name='ReportingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Human readable label, e.g. "March 2026"', max_length=100)),
                ('period_start', models.DateField(help_text='Start of reporting period')),
                ('period_end', models.DateField(help_text='End of reporting period')),
                ('due_date', models.DateField(help_text='Soft deadline - triggers warning in app')),
                ('close_date', models.DateField(help_text='Hard deadline - form locks after this date')),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('open', 'Open'), ('closed', 'Closed')], default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='forms_builder.form')),
            ],
            options={
                'ordering': ['-period_start'],
                'unique_together': {('form', 'period_start')},
            },
        ),
    ]
