# Generated by Django 4.2.11 on 2026-03-11 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_builder', '0002_alter_formassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportingperiod',
            name='status',
        ),
    ]
